server:
  port: 8080

spring:
  application:
    name: gestao-alunos # Nome da aplicação
  jackson:
    property-naming-strategy: SNAKE_CASE # Converte os nomes das propriedades para snake_case
  thymeleaf:
    cache: false # Desabilita o cache do Thymeleaf
  data:
    mongodb:
      uri: mongodb://aluno:aluno@localhost:27017/alunodb?authSource=alunodb # URI de conexão com o MongoDB