services:
  mongodb:
    image: mongo:8.0.4 # Imagem do MongoDB
    container_name: mongo-container # Nome do container no Docker
    restart: always # Reinicia o container automaticamente quando ele para
    ports:
      - "27017:27017" # Mapeia a porta local 27017 para a porta do container
    environment:
      MONGO_INITDB_ROOT_USERNAME: aluno # Usuário administrador do MongoDB
      MONGO_INITDB_ROOT_PASSWORD: aluno # Senha do administrador
      MONGO_INITDB_DATABASE: alunodb   # Nome do banco de dados inicial
    volumes:
      - mongodb_data:/data/db # Persistência dos dados do MongoDB
      - ./mongo-scripts/init.js:/docker-entrypoint-initdb.d/init.js:ro # Script de inicialização do MongoDB

volumes:
  mongodb_data:
    name: mongodb_data # Define um nome fixo para o volume
    driver: local # Armazena os dados localmente. O Docker criará o volume automaticamente